### ISSUE TITLE
Архитектура решения

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#11]
**Требуется:**
- продумать целевую архитектуру системы (см. ниже)
- пройти ревью от коллег и заказчиков

После разговора с заказчиком:
**Программный модуль, который**:
- на вход принимает записанный аудиосигнал
- переварить его (показать методику)
- результат распознавания, нормальный результат
- позиция распознаваемого компонента, например на 99 семпле распознали что-то (идеальная картина: линейдж аудиосигнала, какой кусочек был ключевым, каким он был до предобработки и после)

**Comment by AnatolyAdamovich** [comment]
Программный модуль, который:
- на вход принимает записанный аудиосигнал
- переварить его (показать методику)
- результат распознавания, нормальный результат

Посмотреть эффект доплера

Статистика по моделям и их экспериментам обязательно в виде таблицы

позиция распознаваемого компонента, например на 99 семпле распознали что-то
идеальная картина: линейдж аудиосигнала, какой кусочек был ключевым, каким он был до предобработки и после

**Comment by AnatolyAdamovich** [comment]
формат файла, размерность

1. float vs short ?
2. фрустрация, много шумов

**Comment by VaultSchebnik** [comment]
Первый драфт модели ![Image](https://github.com/user-attachments/assets/9ad1e304-2db6-4320-a705-8af27f50f23b)
