### ISSUE TITLE
Практика методов извлечения фич из аудио

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#14]
**Требуется попробовать:**
- построить спектограммы 
- извлечь mfcc

В качестве данных взять выборку из любого найденного датасета

В результате небольшой прототип в виде jupyter-ноутбука с экспериментами

**Comment by ttaltam** [comment]
спектрограммы и MFCC для аудиодатасета, использовать Python с библиотеками librosa, matplotlib и numpy. 
В качестве данных аудионабор данных, состоящий из 45 звуков из различных источников, включая сирены скорой помощи, детский плач, детский смех, записи леса, звуки больницы и шум, среди прочего.


[spectograms&mfcc.zip](https://github.com/user-attachments/files/17386614/spectograms.mfcc.zip)

**Comment by ttaltam** [comment]
https://github.com/citec-spbu/classifier_of_sound_sources_it_clinic_2024/blob/main/experiments/Analysis_spectograms%26mfcc.ipynb

[spectograms&mfcc.zip](https://github.com/user-attachments/files/17452797/spectograms.mfcc.zip)
