### ISSUE TITLE
Встречи с заказчиком

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#16]

**Comment by YD-B** [comment]
# Собрание 02.10.24
## Заказчик-Команда
- Установлен основной формат взаимодействий
- Определенны интересы заказчика 
    - Роли, интересы и мотивация участников команды
    - Прозрачность процесса работы над проектом
- Утвержден предварительный график встреч

## Проект
- Описание: «Модель» должна обрабатывать поступающие сигналы из микрофонов и адаптироваться под разные условия. Необходимо классифицировать звуки как интересные или нет, и их класс. Пример: в сигнале фиксируется плач ребенка, определяем в каком моменте он звучал и что это за звук.
- Цель: разработка алгоритма, который
    1) классифицирует звук (плач, скорая, шум машины и т.д.)
    2) имеет механизм адаптации под разную среду распространения
- Команде необходимо поискать датасеты в свободном доступе, существующие решения и другие релевантные материалы
- Возможно позже заказчик предоставит свой датасет

**Comment by YD-B** [comment]
# Собрание 23.10.24
## Заказчик-Команда
- Для оперативности лучше сразу отправлять возникающие вопросы в телегу, а не копить их
- Попытаемся договорится о встречи по техническим вопросам (пн, вт, ср)

## Проект
- Необходимо определить формат датасета
    1) это влияет на ожидаемый динамический диапазон
    2) чтобы заказчик знал в каком формате предоставить датасет
- Рассмотреть Эффект Доплера, Эффект Доплера в тумане
- Ожидаемый результат: Программный модуль с api, который принимает аудиосигнал и его перерабатывает, выдавая результат распознавания.
- Желательно, чтобы можно было получить позицию сигнала (в каком промежутке был), каким был и каким стал (хуже/ лучше...) для наглядной визуализации работы модуля (будет полезно на защите)
- Рекомендуется вести статистику по датасетам, метрикам и т.д. (тоже пригодится на защите)

**Comment by YD-B** [comment]
# Собрание 26.11.24
- обсуждение проделанной работы и демо-дня
- рекомендации по проекту и презентации
