### ISSUE TITLE
Регулярная встреча команды

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#17]

**Comment by YD-B** [comment]
# Собрание 19.09.24

## Обсуждение:
- проектов на выбор
- сильных сторон участников и их интересы, а также возможные роли

## Решения:
- Выбрать проекты путем голосования в Телеграмме
- Распределить роли на основе предложений и диалога в Телеграмме

**Comment by YD-B** [comment]
# Собрание 03.10.24
## Обсуждение:
- проекта и плана работы
- взаимодействия с заказчиком
- взаимодействия со СФМО (студенты факультета Международных отношений)

## Решения:
- Распределение задач на спринт
    - Исследование физики процессов 
    - Технический стек
    - Поиск датасетов 
    - Первичный поиск решений 
    - Первоначальный устав проекта 
    - Формирование технических вопросов заказчику
- Предварительная подготовка вопросов от СФМО к следующему собранию

**Comment by YD-B** [comment]
# Собрание 10.10.24
## Обсуждение:
- вопросов CФМО
- проделанной работы за спринт и представленных результатов
- плана работы
- участия в программе «Я в деле»


## Решения:
- Распределение задач на спринт
    - Исследование физики процессов ч.2
    - Создать заявку в "Я в деле"
    - Архитектура решения
    - Попробовать VGGish, Youtube-8M, AudioSet, MobileNetV2 и др.
    - Практика методов фильтрации
    - Практика методов извлечения фич из аудио
    - Коммуникации по репозиторию
    - Встречи с заказчиком
    - Регулярная встреча команды

**Comment by YD-B** [comment]
# Собрание 26.10.24
## Обсуждение:
- проделанной работы за спринт
- архитектуры модуля
- предложений заказчика
- плана работы


## Решения:
- Распределение задач на спринт
    - Попробовать модели для классификации (VGGish и др.) 
    - Архитектура решения
    - Эффект Доплера
    - Написать модуль предобработки vol.1
    - Посмотреть streamlit в качестве обертки

**Comment by YD-B** [comment]
# Собрание 10.11.24
## Обсуждение:
- проделанной работы за спринт
- архитектуры модуля
- разработки и интеграции модели с оберткой
- плана работы

## Решения:
- Продолжение работы над открытыми задачами спринта

**Comment by YD-B** [comment]
# Собрание 17.11.24
## Обсуждение:
- проделанной работы за спринт
- архитектуры модуля
- разработки и интеграции модели с оберткой
- демо-дня
- плана работы

## Решения:
- Распределение задач на спринт
    - Поэкспериментировать с найденными моделями vol.2
    - Подготовка к Demo day
    - Написать обертку в виде класса для модели
    - Соединение модуля предобработки с моделью
    - Веб-интерфейс с помощью streamlit
    - Написать тесты для предобработки 
    - Написать тесты для ядра (модели)

**Comment by YD-B** [comment]
# Собрание 25.11.24
## Обсуждение:
- проделанной работы
- интеграции модуля, модели и интерфейса
- доработка модуля и модели
- демо-дня
- плана работы

## Решения:
- Продолжение работы над открытыми задачами. В приоритете:
    - Подготовка к Demo day
    - Соединение модуля предобработки с моделью
    - Веб-интерфейс с помощью streamlit
