### ISSUE TITLE
Написать обертку в виде класса для модели

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#24]
**Необходимо:**
- написать класс, который будет являться абстракцией над моделью (для удобства использования)
- класс должен уметь: принимать аудио на вход, отдавать на выходе N самых вероятных классов и их вероятности, визуализация "интересного" куска

**Comment by DeLornk** [comment]
В рамках коммита [e954728](https://github.com/citec-spbu/classifier_of_sound_sources_it_clinic_2024/commit/e954728fd861572ee56437cc9d6e7e567c3c13b8) создан ноутбук с инференсом дообученной под UrbanSound модели YAMNet, там же находится соответствующий класс для интеграции в общий пайплайн.
