### ISSUE TITLE
Соединение модуля предобработки с моделью

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#25]
**Необходимо:**
- соединить два разных модуля (предобработка + модель) и убедиться, что они не кофликтуют

**Comment by VaultSchebnik** [comment]
https://colab.research.google.com/drive/1s4bimxaAjJ56zRpUQWGDlVBRQzJuUg0J?usp=sharing
