### ISSUE TITLE
Написать тесты для предобработки

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#27]
**Необходимо:**
- продумать тесты для этапа предобработки (можно с помощью ИИ)
- используя библиотеку pytest протестировать модуль предобработки (**core/preproccessing**)

**Comment by ttaltam** [comment]
### Основные тесты
1. **Тест загрузки аудиофайла (`load_audio`)**:
    - Проверить, что аудиосигнал и частота дискретизации корректно загружаются.
    - Проверить обработку исключений для несуществующего пути.

2. **Тест сохранения аудиофайла (`save_audio`)**:
    - Убедиться, что аудиофайл корректно сохраняется.
    - Проверить, что файл создаётся с правильной частотой дискретизации.

3. **Тест нормализации (`normalize`)**:
    - Проверить, что метод корректно нормализует амплитуды.
    - Убедиться, что разные методы нормализации ("peak", "rms") работают правильно.

4. **Тест преэмфазиса (`preemphasis`)**:
    - Проверить, что сигнал становится более выраженным на высоких частотах.

5. **Тест удаления шума (`remove_noise`)**:
    - Проверить, что шумовые компоненты успешно удаляются.
    - Убедиться, что метод поддерживает оба режима: с передачей интервала шума и без.

6. **Тест эквализации (`equalize`)**:
    - Проверить, что сигнал фильтруется в заданном частотном диапазоне.

7. **Тесты оконного анализа (`windowing`)**:
    - Проверить, что оконная функция корректно применяется к сигналу.

8. **Тесты для визуализации**:
    - Убедиться, что функции визуализации не вызывают исключений.

### Тесты для анализа признаков
1. **Тест вычисления MFCC (`mfcc`)**:
    - Проверить, что вычисляется корректное количество коэффициентов.
    - Убедиться, что результат имеет ожидаемую форму.

2. **Тест нулевых пересечений (`zcr`)**:
    - Убедиться, что метод возвращает корректные значения для разных сигналов.

3. **Тест хроматических признаков (`chroma`)**:
    - Проверить, что распределение энергии в хроматической шкале корректно вычисляется.

**Comment by ttaltam** [comment]
### Тесты для функций предобработки

1. **Тест загрузки аудиофайла (`load_audio`)**:
    - Проверить, что аудиосигнал и частота дискретизации корректно загружаются.
    - Проверить обработку исключений для несуществующего пути.

2. **Тест сохранения аудиофайла (`save_audio`)**:
    - Убедиться, что аудиофайл корректно сохраняется.
    - Проверить, что файл создаётся с правильной частотой дискретизации.

3. **Тест нормализации (`normalize`)**:
    - Проверить, что метод корректно нормализует амплитуды.
    - Убедиться, что разные методы нормализации ("peak", "rms") работают правильно.

4. **Тест преэмфазиса (`preemphasis`)**:
    - Проверить, что сигнал становится более выраженным на высоких частотах.

5. **Тест удаления шума (`remove_noise`)**:
    - Проверить, что шумовые компоненты успешно удаляются.
    - Убедиться, что метод поддерживает оба режима: с передачей интервала шума и без.

6. **Тест эквализации (`equalize`)**:
    - Проверить, что сигнал фильтруется в заданном частотном диапазоне.

7. **Тесты оконного анализа (`windowing`)**:
    - Проверить, что оконная функция корректно применяется к сигналу.

8. **Тесты для визуализации**:
    - Убедиться, что функции визуализации не вызывают исключений.


### Тесты для анализа признаков

1. **Тест вычисления MFCC (`mfcc`)**:
    - Проверить, что вычисляется корректное количество коэффициентов.
    - Убедиться, что результат имеет ожидаемую форму.

2. **Тест нулевых пересечений (`zcr`)**:
    - Убедиться, что метод возвращает корректные значения для разных сигналов.

3. **Тест хроматических признаков (`chroma`)**:
    - Проверить, что распределение энергии в хроматической шкале корректно вычисляется.

   ```python

      import pytest
      import numpy as np
      import os
      from core.preprocessing import AudioPreprocessor
      
      TEST_AUDIO_PATH = "test_audio.wav"
      OUTPUT_AUDIO_PATH = "output_audio.wav"
      
      @pytest.fixture
      def audio_processor():
          sr = 22050
          duration = 2  # seconds
          audio = np.random.rand(sr * duration) * 2 - 1  # Генерация случайного сигнала
          return AudioPreprocessor(audio=audio, sr=sr)
      
      def test_load_audio(audio_processor):
          audio_processor.load_audio(TEST_AUDIO_PATH)
          assert audio_processor.audio is not None
          assert audio_processor.sr is not None
      
      def test_save_audio(audio_processor):
          audio_processor.save_audio(OUTPUT_AUDIO_PATH)
          assert os.path.exists(OUTPUT_AUDIO_PATH)
          os.remove(OUTPUT_AUDIO_PATH)
      
      def test_normalize(audio_processor):
          normalized = audio_processor.normalize(method="peak")
          assert np.max(np.abs(normalized.audio)) == pytest.approx(1.0, rel=1e-3)
      
      def test_preemphasis(audio_processor):
          emphasized = audio_processor.preemphasis(coef=0.97)
          assert len(emphasized.audio) == len(audio_processor.audio)
      
      def test_remove_noise(audio_processor):
          noise_reduced = audio_processor.remove_noise()
          assert len(noise_reduced.audio) == len(audio_processor.audio)
      
      def test_equalize(audio_processor):
          equalized = audio_processor.equalize(lowcut=300, highcut=3000)
          assert len(equalized.audio) == len(audio_processor.audio)
      
      def test_mfcc(audio_processor):
          mfcc_features = audio_processor.mfcc(n_mfcc=13)
          assert mfcc_features.shape[0] == 13
      
      def test_windowing(audio_processor):
          windows = audio_processor.windowing(window_length=1024, hop_size=512)
          assert windows.shape[0] == 1024

   ```
