### ISSUE TITLE
Поиск датасетов

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#4]
**Необходимо:**

1. Поискать датасеты для поставленной задачи
2. Скачать датасеты, изучить их и выделить релевантные (около 5-6 штук, можно больше)

Рекомендуемые источники: kaggle

**Comment by ttaltam** [comment]
1. [UrbanSound8K](https://www.kaggle.com/datasets/chrisfilo/urbansound8k): Содержит 8,732 файла городских звуков, разделённых на 10 категорий, таких как сирены, гудки машин и шаги.


2. [Environmental Sound Classification (ESC-50)](https://www.kaggle.com/datasets/mmoreaux/environmental-sound-classification-50): Включает 50 классов звуков из разных категорий, таких как звуки природы, животных, бытовые шумы и транспорт.


3. [AudioSet](https://www.kaggle.com/datasets/zfturbo/audioset): Огромный датасет с более чем 600 категориями звуков, включая человеческие звуки, природу, транспортные шумы и музыкальные инструменты.


4. [Infant Cry Sounds](https://www.kaggle.com/datasets/raiyanjahangir1939/infant-cry-sounds): Специализированный набор данных с плачем младенцев, который включает разные типы плача, например, вызванного болью или голодом.


5. [Hospital Ambient Noise](https://www.kaggle.com/datasets/nafin59/hospital-ambient-noise): Содержит шумы больничной среды, такие как шаги, разговоры и медицинские приборы.


6. [Ambulance Dataset](https://www.kaggle.com/datasets/tabarkarajab/ambulance-dataset): Датасет с записями сирен скорой помощи, полезен для создания моделей для распознавания сирен.
