### ISSUE TITLE
Формирование технических вопросов заказчику

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#7]
**Для качественного продумывания архитектуры целевого решения требуется:**
- собрать (привлекая к brainstorm коллег) список вопросов заказчику (технических или околотехнических)
- представить полученный список вопросов коллегам
- после утверждения со стороны коллег отправить вопросы в основной канал с заказчиком в ТГ

**Comment by AnatolyAdamovich** [comment]
1) На что влияет выбор кол-во измерений `n_mfcc` ? 
```python
mfccs = librosa.feature.mfcc(y=audio_ts, sr=sampling_rate, n_mfcc=5)
```
2) Как задавать sampling rate для аудио при загрузке? И на что он влияет?
```python
ts, sr = librosa.load(f'data/{filename}', sr=None)
```

3) Как анализировать изображения спектограммы или mfcc? ЧТо по этим картинкам можно сказать?

**Comment by AnatolyAdamovich** [comment]
4. какие методы предобработки советуете?
5. какие модели советуете ?
6. в какую сторону поглубже погрузиться?
7. когда будет представлен датасет и будет ли он представлен?
8. нужен ли интерфейс к модели? или мы изготавливаем исключительно модель и пайплайн доступа к модели?

**Comment by DeLornk** [comment]
9. Какая скорость инференса желательна (не факт, что мы этого добьёмся, но к чему надо стремится)?
10. В случае смены среды, мы подразумеваем, что происходит дообучение модели (то есть, условно, модели нужно время как раз к адаптации под "нормальное" состояние окружающей среды)?
11. Если мы будем адаптироваться к разным средам, то в разных средах совершенно разный набор интересующих нас звуков. Условно, в пустыне любой звук не считая ветра с песком, нас интересуют, но тогда нам нужно уметь классифицировать бесконечное количество классов. А в ТЦ таких звуков уже можно предположить какое-то счётное количество. Или нам достаточно просто метку выделяющихся звуков с указанием времени (то есть здесь только один класс)?
12. Задача относится к sound event detection (SED) или это про другое?
13. Может посоветовать сразу какой-то открытый датасет, который подойдёт под нашу задачу (если нет, то нет). Стоит ли тут заморачиваться с синтезированием данных или уже усложнение и синтезирование тут не понадобится?
14. Помимо mfcc может нам, как новичкам, посоветовать, какие ещё характеристики звука можно использовать?

**Comment by AnatolyAdamovich** [comment]
Решили, что вопросы задаем в сразу в ТГ.
Задачу закрываем
