### ISSUE TITLE
Исследование физики процессов ч.2

### ISSUE THREAD

**Issue by AnatolyAdamovich** [citec-spbu/classifier_of_sound_sources_it_clinic_2024#9]
**Требуется:**
- погрузиться в то, какой метод извлечения признаков характерен для различных сред (т.е. под какую среду какие признаки предпочтительны)

**Comment by VaultSchebnik** [comment]
![Image](https://github.com/user-attachments/assets/99a2e57e-0d9a-4c04-ae29-e4299c204e80)
Вот что удалось узнать по признакам:

1. Количество пересечений нуля
Этот признак измеряет, сколько раз аудиосигнал пересекает нулевую линию. Он может дать представление о частоте и стабильности сигнала. Например, более высокое количество пересечений нуля обычно указывает на более высокие частоты.
**Из какой среды извлекать:** Городской шум или музыкальные записи.

2. Энергия сигнала
Энергия сигнала представляет собой интеграл квадратов амплитуд аудиосигнала во времени. Это ключевой признак для определения громкости звука.
**Из какой среды извлекать:** Контекстные записи, такие как концерты, лекции и другие мероприятия с высоким уровнем звуковой активности.

3. Энтропия энергии
Этот признак отражает степень изменчивости энергии во времени. Высокая энтропия указывает на нерегулярные и сложные звуковые структуры.
**Из какой среды извлекать:** Музыкальные произведения или сложные звуковые ландшафты, например, в лесу или в горах.

4. Спектральный центроид
Центроид указывает на "центр масс" спектра сигнала и дает понять, где сосредоточены частоты звучания. Он может быть интерпретирован как то, насколько "ярким" или "темным" звучание.
**Из какой среды извлекать:** Музыка различных жанров или речевые записи.

5. Мгновенная ширина спектра
Этот признак измеряет диапазон частот, присутствующих в аудиосигнале в определенный момент времени. Он помогает анализировать текстуру звука.
**Из какой среды извлекать:** Аудиозаписи природных звуков, например, звуки животных, ветра и т.д.

6. Audio Spectrum Flatness
Этот показатель отражает равномерность распределения энергии по частотам, где высокое значение указывает на "шумные" сигналы, а низкое — на "узкие" звуки.
**Из какой среды извлекать:** Музыкальные записи, особенно электронную музыку.

7. Energy-band spectrum
Этот признак делит энергию сигнала по частотным диапазонам, позволяя более подробно анализировать специфические диапазоны, например, басы и высокие частоты.
**Из какой среды извлекать:** Музыкальные записи и записи инструментов, таких как гитара или пианино.

8. Кепстральные коэффициенты (C0, C1, ..., Cn)
Эти коэффициенты используются для характеристики звуковых сигналов в области позитронной (частотной) и временной области, часто применяемыми в распознавании речи и ритмических паттернов.
**Из какой среды извлекать:** Речевые записи и аудиосигналы с четкими вокальными элементами.

9. Спектральная энтропия
Этот признак отражает уровень разнообразия спектра частот. Высокая энтропия указывает на более разнообразный спектр, а низкая — на менее разнообразный.
**Из какой среды извлекать:** Музыкальные произведения различных стилей.

10. Поток спектра
Время и изменение спектра аудиосигнала. Этот признак помогает в анализе изменений во времени, например, в динамике музыки или других звуков.
**Из какой среды извлекать:** Живые концерты, звуки природы, которые меняются по времени.

11. Spectral rolloff
Этот признак определяет частоту, ниже которой находится определенный процент (обычно 85%) от общей энергии спектра. Помогает отличать музыкальные и шумовые сигналы.
**Из какой среды извлекать:** Музыка и различные звуковые эффекты.

12. Основная частота
Это наиболее ярко выраженная частота в спектре сигнала, часто воспринимаемая как основная нота звука.
**Из какой среды извлекать:** Инструменты (например, фортепиано или гитара), а также вокальные записи.

13. MFCC (Mel-Frequency Cepstral Coefficients)
Используется для представления характеристики звукового сигнала и максимально приближен к восприятию слухом человека. Это основной признак в распознавании речи и музыки.
**Из какой среды извлекать:** Записи речи и музыкальные произведения.

**Comment by AnatolyAdamovich** [comment]
0) формат файла, размерность
1) float vs short ? 
2) фрустрация, много шумов
